namespace RediveStoryDeserializer
{
    public record CommandConfig
    {
        public CommandNumber Number { get; init; }
        public string Name { get; init; }
        public string ClassName { get; init; }
        public CommandCategory CommandCategory { get; init; }
        public (int, int) ArgCount { get; init; }

        private CommandConfig(CommandNumber number, string commandName, string className, CommandCategory category,
            int minArgCount, int maxArgCount)
        {
            Number = number;
            Name = commandName;
            ClassName = className;
            CommandCategory = category;
            ArgCount = (minArgCount, maxArgCount);
        }

        public static readonly CommandConfig[] List = new[]
        {
            new CommandConfig(CommandNumber.Title, "title", "StoryCommandTitle", CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.Outline, "outline", "StoryCommandOutline", CommandCategory.System,
                1, 1),
            new CommandConfig(CommandNumber.Visible, "visible", "StoryCommandVisible", CommandCategory.System,
                2, 2),
            new CommandConfig(CommandNumber.Face, "face", "StoryCommandFace", CommandCategory.System, 2, 2),
            new CommandConfig(CommandNumber.Focus, "focus", "StoryCommandFocus", CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.Background, "background", "StoryCommandBackground",
                CommandCategory.System, 1, 3),
            new CommandConfig(CommandNumber.Print, "print", "StoryCommandPrint", CommandCategory.System, 2, 2),
            new CommandConfig(CommandNumber.Tag, "tag", "StoryCommandTag", CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.Goto, "goto", "StoryCommandGoto", CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.Bgm, "bgm", "StoryCommandBgm", CommandCategory.System, 1, 6),
            new CommandConfig(CommandNumber.Touch, "touch", "StoryCommandTouch", CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.Choice, "choice", "StoryCommandChoice", CommandCategory.System, 2,
                3),
            new CommandConfig(CommandNumber.Vo, "vo", "StoryCommandVo", CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.Wait, "wait", "StoryCommandWait", CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.InL, "in_L", "StoryCommandInL", CommandCategory.Motion, 1, 3),
            new CommandConfig(CommandNumber.InR, "in_R", "StoryCommandInR", CommandCategory.Motion, 1, 3),
            new CommandConfig(CommandNumber.OutL, "out_L", "StoryCommandOutL", CommandCategory.Motion, 1, 3),
            new CommandConfig(CommandNumber.OutR, "out_R", "StoryCommandOutR", CommandCategory.Motion, 1, 3),
            new CommandConfig(CommandNumber.Fadein, "fadein", "StoryCommandFadein", CommandCategory.Motion, 1,
                2),
            new CommandConfig(CommandNumber.Fadeout, "fadeout", "StoryCommandFadeout", CommandCategory.Motion,
                0, 2),
            new CommandConfig(CommandNumber.InFloat, "in_float", "StoryCommandInFloat",
                CommandCategory.Motion, 1, 2),
            new CommandConfig(CommandNumber.OutFloat, "out_float", "StoryCommandOutFloat",
                CommandCategory.Motion, 1, 2),
            new CommandConfig(CommandNumber.Jump, "jump", "StoryCommandJump", CommandCategory.Motion, 1, 2),
            new CommandConfig(CommandNumber.Shake, "shake", "StoryCommandShake", CommandCategory.Motion, 1, 2),
            new CommandConfig(CommandNumber.Pop, "pop", "StoryCommandPop", CommandCategory.Motion, 1, 2),
            new CommandConfig(CommandNumber.Nod, "nod", "StoryCommandNod", CommandCategory.Motion, 1, 2),
            new CommandConfig(CommandNumber.Se, "se", "StoryCommandSe", CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.BlackOut, "black_out", "StoryCommandBlackOut",
                CommandCategory.System, 0, 2),
            new CommandConfig(CommandNumber.BlackIn, "black_in", "StoryCommandBlackIn",
                CommandCategory.System, 0, 2),
            new CommandConfig(CommandNumber.WhiteOut, "white_out", "StoryCommandWhiteOut",
                CommandCategory.System, 0, 2),
            new CommandConfig(CommandNumber.WhiteIn, "white_in", "StoryCommandWhiteIn",
                CommandCategory.System, 0, 2),
            new CommandConfig(CommandNumber.Transition, "transition", "StoryCommandTransition",
                CommandCategory.System, 1, 2),
            new CommandConfig(CommandNumber.Situation, "situation", "StoryCommandSituation",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.ColorFadein, "color_fadein", "StoryCommandColorFadein",
                CommandCategory.System, 3, 3),
            new CommandConfig(CommandNumber.Flash, "flash", "StoryCommandFlash", CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.ShakeText, "shake_text", "StoryCommandShakeText",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.TextSize, "text_size", "StoryCommandTextSize",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.ShakeScreen, "shake_screen", "StoryCommandShakeScreen",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.Double, "double", "StoryCommandDouble", CommandCategory.System, 2,
                4),
            new CommandConfig(CommandNumber.Scale, "scale", "StoryCommandScale", CommandCategory.Motion, 1, 4),
            new CommandConfig(CommandNumber.TitleTelop, "title_telop", "StoryCommandTitleTelop",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.WindowVisible, "window_visible", "StoryCommandWindowVisible",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.Log, "log", "StoryCommandLog", CommandCategory.System, 3, 4),
            new CommandConfig(CommandNumber.NoVoice, "novoice", "StoryCommandNoVoice", CommandCategory.System,
                0, 0),
            new CommandConfig(CommandNumber.Change, "change", "StoryCommandChange", CommandCategory.Motion, 2,
                3),
            new CommandConfig(CommandNumber.FadeoutAll, "fadeout_all", "StoryCommandFadeoutAll",
                CommandCategory.Motion, 0, 1),
            new CommandConfig(CommandNumber.Movie, "movie", "StoryCommandMovie", CommandCategory.System, 1, 4),
            new CommandConfig(CommandNumber.MovieStay, "movie_stay", "StoryCommandMovieStay",
                CommandCategory.System, 1, 4),
            new CommandConfig(CommandNumber.Battle, "battle", "StoryCommandBattle", CommandCategory.System, 0,
                0),
            new CommandConfig(CommandNumber.Still, "still", "StoryCommandStill", CommandCategory.System, 1, 6),
            new CommandConfig(CommandNumber.BustUp, "bust", "StoryCommandBustup", CommandCategory.System, 1,
                3),
            new CommandConfig(CommandNumber.Env, "amb", "StoryCommandEnv", CommandCategory.System, 1, 4),
            new CommandConfig(CommandNumber.TutorialReward, "reward", "StoryCommandTutorialReward",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.NameEdit, "name_dialog", "StoryCommandPlayerNameEdit",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.Effect, "effect", "StoryCommandParticleEffect",
                CommandCategory.Effect, 1, 5),
            new CommandConfig(CommandNumber.EffectDelete, "effect_delete", "StoryCommandParticleDelete",
                CommandCategory.Effect, 1, 2),
            new CommandConfig(CommandNumber.EyeOpen, "eye_open", "StoryCommandEyeOpen",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.MouthOpen, "mouth_open", "StoryCommandMouthOpen",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.AutoEnd, "end", "StoryCommandForcedEnd", CommandCategory.System,
                0, 0),
            new CommandConfig(CommandNumber.Emotion, "emotion", "StoryCommandEmotion", CommandCategory.Effect,
                1, 5),
            new CommandConfig(CommandNumber.EmotionEnd, "emotion_end", "StoryCommandEmotionEnd",
                CommandCategory.Effect, 1, 1),
            new CommandConfig(CommandNumber.EnvStop, "amb_stop", "StoryCommandEnvStop",
                CommandCategory.System, 1, 2),
            new CommandConfig(CommandNumber.BgmPause, "bgm_stop", "StoryCommandBgmPause",
                CommandCategory.System, 0, 2),
            new CommandConfig(CommandNumber.BgmResume, "bgm_resume", "StoryCommandBgmResume",
                CommandCategory.System, 0, 2),
            new CommandConfig(CommandNumber.BgmVolumeChange, "bgm_volume", "StoryCommandBgmVolumeChange",
                CommandCategory.System, 1, 2),
            new CommandConfig(CommandNumber.EnvResume, "amb_resume", "StoryCommandEnvResume",
                CommandCategory.System, 0, 2),
            new CommandConfig(CommandNumber.EnvVolume, "amb_volume", "StoryCommandEnvVolumeChange",
                CommandCategory.System, 1, 2),
            new CommandConfig(CommandNumber.SePause, "se_pause", "StoryCommandSeStop", CommandCategory.System,
                0, 2),
            new CommandConfig(CommandNumber.CharaFull, "chara_full", "StoryCommandCharacterFull",
                CommandCategory.System, 3, 4),
            new CommandConfig(CommandNumber.Sway, "sway", "StoryCommandSway", CommandCategory.Motion, 1, 1),
            new CommandConfig(CommandNumber.BackgroundColor, "bg_color", "StoryCommandBackgroundColor",
                CommandCategory.System, 3, 4),
            new CommandConfig(CommandNumber.Pan, "pan", "StoryCommandStillPan", CommandCategory.Motion, 1, 1),
            new CommandConfig(CommandNumber.StillUnit, "still_unit", "StoryCommandStillUnit",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.SlideChara, "slide", "StoryCommandSlideCharacter",
                CommandCategory.Motion, 1, 1),
            new CommandConfig(CommandNumber.ShakeScreenOnce, "shake_once", "StoryCommandShakeScreenOnce",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.TransitionResume, "transition_resume",
                "StoryCommandTransitionResume", CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.ShakeLoop, "shake_loop", "StoryCommandShakeLoop",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.ShakeDelete, "shake_delete", "StoryCommandShakeDelete",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.UnFace, "unface", "StoryCommandUnface", CommandCategory.System, 1,
                1),
            new CommandConfig(CommandNumber.WaitToken, "token", "StoryCommandWaitToken",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.EffectEnv, "effect_env", "StoryCommandParticleEffectEnv",
                CommandCategory.Effect, 1, 1),
            new CommandConfig(CommandNumber.BrightChange, "bright_change", "StoryCommandBrightChange",
                CommandCategory.System, 2, 2),
            new CommandConfig(CommandNumber.CharaShadow, "chara_shadow", "StoryCommandCharacterShadow",
                CommandCategory.System, 2, 2),
            new CommandConfig(CommandNumber.UiVisible, "ui_visible", "StoryCommandMenuVisible",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.FadeinAll, "fadein_all", "StoryCommandFadeinAll",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.ChangeWindow, "change_window", "StoryCommandChangeWindow",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.BgPan, "bg_pan", "StoryCommandBackgroundPan",
                CommandCategory.System, 2, 3),
            new CommandConfig(CommandNumber.StillMove, "still_move", "StoryCommandStillMove",
                CommandCategory.System, 2, 3),
            new CommandConfig(CommandNumber.StillNormalize, "still_normalize", "StoryCommandStillNormalize",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.VoiceEffect, "vo_effect", "StoryCommandVoiceEffect",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.TrialEnd, "trial_end", "StoryCommandTrialEnd",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.SeEffect, "se_effect", "StoryCommandSeEffect",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.CharacterUpDown, "updown", "StoryCommandCharacterUpdown",
                CommandCategory.Motion, 4, 4),
            new CommandConfig(CommandNumber.BgCameraZoom, "bg_zoom", "StoryCommandBgCameraZoom",
                CommandCategory.System, 2, 2),
            new CommandConfig(CommandNumber.BackgroundSplit, "split", "StoryCommandBackgroundSplit",
                CommandCategory.System, 2, 6),
            new CommandConfig(CommandNumber.CameraZoom, "camera_zoom", "StoryCommandCameraZoom",
                CommandCategory.System, 2, 2),
            new CommandConfig(CommandNumber.SplitSlide, "split_slide", "StoryCommandBackgroundSplitSlide",
                CommandCategory.System, 0, 6),
            new CommandConfig(CommandNumber.BgmTransition, "bgm_transition", "StoryCommandBgmTransition",
                CommandCategory.System, 2, 2),
            new CommandConfig(CommandNumber.ShakeAnime, "shake_anime", "StoryCommandBackgroundAnimation",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.InsertStory, "insert", "StoryCommandInsertStory",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.Place, "place", "StoryCommandPlace", CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.IgnoreBgm, "bgm_overview", "StoryCommandBgmIgnoreStop",
                CommandCategory.System, 1, 5),
            new CommandConfig(CommandNumber.MultiLipsync, "multi_talk", "StoryCommandMultiLipsync",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.Jingle, "jingle_start", "StoryCommandJingle",
                CommandCategory.System, 1, 1),
            new CommandConfig(CommandNumber.TouchToStart, "touch_to_start", "StoryCommandTouchToStart",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.EventAdvMoveHorizontal, "event_change",
                "StoryCommandEventCharacterChange", CommandCategory.System, 1, 3),
            new CommandConfig(CommandNumber.BgPanX, "bg_pan_slide", "StoryCommandBackgroundPanX",
                CommandCategory.System, 1, 3),
            new CommandConfig(CommandNumber.BackgroundBlur, "bg_blur", "StoryCommandBackgroundBlur",
                CommandCategory.System, 1, 3),
            new CommandConfig(CommandNumber.SeasonalReward, "seasonal_reward", "StoryCommandSeasonalReward",
                CommandCategory.System, 0, 0),
            new CommandConfig(CommandNumber.MiniGame, "mini_game", "StoryCommandMiniGame",
                CommandCategory.System, 0, 1),
            new CommandConfig(CommandNumber.DialogAnimation, "dialog_anime", "StoryCommandDialogAnimation",
                CommandCategory.System, 0, 1)
        };
    }
}
