name: Fetch Latest Database

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  fetch-database:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout RediveData
      uses: actions/checkout@v2
      with:
        repository: "KiruyaMomochi/RediveData"
        path: "./RediveData"
        token: ${{ secrets.REDIVEDATA_ACCESS_TOKEN }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Download RediveExtract
      uses: KiruyaMomochi/download-release@v1
      with:
        repo: KiruyaMomochi/RediveExtract
        file: RediveExtract.zip
    - name: Extract RediveExtract
      run: Expand-Archive ./RediveExtract.zip
    - name: Install sqlite
      run: |
        choco install sqlite
    - name: Run Script
      working-directory: "./RediveData"
      run: |
        Import-Module ../scripts/ngdive.psm1
        Import-Manifest ./manifest/masterdata2_assetmanifest |
          Save-AssetItem -OutputDirectory . |
          Expand-AssetItem -Program ${{ github.workspace }}/RediveExtract/RediveExtract.exe -OutputDirectory ./db
    - name: Commit Files
      working-directory: "./RediveData"
      run: |
        Import-Module ../scripts/ngdive.psm1
        git pull
        Invoke-RediveCommit -Type Database
        git push
    - name: Upload database
      uses: actions/upload-artifact@v2
      with:
        name: master-database
        path: |
          RediveData/db/*.sqlite
