name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0-rc.2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run
      run: dotnet run --configuration Release --no-restore
    - name: Commit files
      run: |
        if [[ -z $(git status -s) ]] 
        then
        git config --global user.name 'KiruyaMomochi'
        git config --global user.email 'KiruyaMomochi@users.noreply.github.com'
        git commit -am "Auto update: $(date)"
        git push
        fi
