# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fetch Master Database

on:
  push:
    branches: [ master ]
    paths:
      - 'manifest/masterdata_assetmanifest'

defaults:
    run:
        shell: pwsh      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install UnityPy
    - name: Run Script
      run: |
        pwsh Scripts/Export-RediveDB.ps1
    - name: Commit Files
      run: |
        if (git status -s)
        {
            $json = cat .\config.json | ConvertFrom-Json
            $taipei = [System.TimeZoneInfo]::FindSystemTimeZoneById('Asia/Taipei')
            $time = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'Taipei Standard Time').ToString("yyyy-MM-dd HH:mm:ss")
            $message = "Database: $($json.Version -join '.')($($json.TruthVersion)) at $time"
            git status -s
            git config --global user.name 'KiruyaMomochi'
            git config --global user.email 'KiruyaMomochi@users.noreply.github.com'
            git add db/*
            git commit -m $message
            git push
        }
    - name: Upload database
      uses: actions/upload-artifact@v2
      with:
        name: master-database
        path: |
          !*.sqlite
