name: Fetch Latest Manifests

on:
  push:
    branches: [ master ]
    paths-ignore:
     - 'README.md'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 * * * *

defaults:
  run:
    shell: pwsh

jobs:
  fetch-manifest:

    runs-on: windows-latest

    outputs:
      db: ${{ steps.kyaru.outputs.db }}
      story: ${{ steps.pecorine.outputs.story }}
    steps:
    - uses: actions/checkout@v2
    - name: Checkout RediveData
      uses: actions/checkout@v2
      with:
        repository: "KiruyaMomochi/RediveData"
        path: "./RediveData"
        token: ${{ secrets.REDIVEDATA_ACCESS_TOKEN }}
    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run
      run: dotnet run --project RediveExtract --configuration Release --no-restore --  --config ./RediveData/config.json --output RediveData
    - name: Set output for fetch database
      id: kyaru
      working-directory: "./RediveData"
      run: |
        if ((git status './manifest/masterdata_assetmanifest' -s) -or !(Test-Path db))
        {
          echo "output set"
          echo "::set-output name=db::true"
        }
    - name: Set output for fetch storytext
      id: pecorine
      working-directory: "./RediveData"
      run: |
        if ((git status './manifest/storydata_assetmanifest' -s) -or !(Test-Path storydata))
        {
          echo "output set"
          echo "::set-output name=story::true"
        }
    - name: Commit files
      working-directory: "./RediveData"
      run: |
        pwsh ../Scripts/Commit-Data.ps1 -Type Manifest

  fetch-database:

    runs-on: windows-latest

    needs: fetch-manifest
    if: ${{ needs.fetch-manifest.outputs.db }}

    steps:
    - uses: actions/checkout@v2
    - name: Checkout RediveData
      uses: actions/checkout@v2
      with:
        repository: "KiruyaMomochi/RediveData"
        path: "./RediveData"
        token: ${{ secrets.REDIVEDATA_ACCESS_TOKEN }}
    - name: Install sqlite
      run: |
        choco install sqlite
    - name: Run Script
      working-directory: "./RediveData"
      run: |
        pwsh ../Scripts/Export-RediveDB.ps1
    - name: Commit Files
      working-directory: "./RediveData"
      run: |
        pwsh ../Scripts/Commit-Data.ps1 -Type Database
    - name: Upload database
      uses: actions/upload-artifact@v2
      with:
        name: master-database
        path: |
          RediveData/*.sqlite

  fetch-storydata:

    runs-on: windows-latest

    needs: fetch-manifest
    if: ${{ needs.fetch-manifest.outputs.story }}
    steps:
    - uses: actions/checkout@v2
    - name: Checkout RediveData
      uses: actions/checkout@v2
      with:
        repository: "KiruyaMomochi/RediveData"
        path: "./RediveData"
        token: ${{ secrets.REDIVEDATA_ACCESS_TOKEN }}
    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run Script
      working-directory: "./RediveData"
      run: |
        pwsh ../Scripts/Export-RediveStory.ps1
    - name: Commit Files
      working-directory: "./RediveData"
      run: |
        pwsh ../Scripts/Commit-Data.ps1 -Type Storytext
    - name: Upload database
      uses: actions/upload-artifact@v2
      with:
        name: master-database
        path: |
          RediveData/*.bytes
        
