name: Fetch Latest Manifests

on:
  push:
    paths-ignore:
    - 'db/**'
    - 'README.md'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 * * * *

defaults:
  run:
    shell: pwsh

jobs:
  fetch-manifest:

    runs-on: windows-latest

    
    outputs:
      updated: ${{ steps.kyaru.outputs.flag }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      repository: 'KiruyaMomochi/RediveData'
      path: data
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    # - name: Setup .NET 5.0.100-rc.2.20479.15
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 5.0.100-rc.2.20479.15
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run
      run: dotnet run --project RediveExtract --configuration Release --no-restore -- --outdir RediveData
    - name: Set output for fetch database
      id: kyaru
      run: |
        if ((git status '.\manifest\masterdata_assetmanifest' -s) -or !(Test-Path db))
        {
          echo "output set"
          echo "::set-output name=flag::true"
        }
    - name: Commit files
      run: |
        if (git status -s)
        {
            $json = Get-Content ./config.json | ConvertFrom-Json
            $time = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'Taipei Standard Time').ToString("yyyy-MM-dd HH:mm:ss")
            $message = "Manifest: $($json.Version -join '.')($($json.TruthVersion)) at $time"
            git status -s
            git config --global user.name 'KiruyaMomochi'
            git config --global user.email 'KiruyaMomochi@users.noreply.github.com'
            git add .
            git commit -m $message
            git push
        }
        