name: Fetch Latest Manifests

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  fetch-manifest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: Checkout RediveData
      uses: actions/checkout@v2
      with:
        repository: "KiruyaMomochi/RediveData"
        path: "./RediveData"
        token: ${{ secrets.REDIVEDATA_ACCESS_TOKEN }}
    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download RediveExtract
      uses: KiruyaMomochi/download-release@v1
      with:
        repo: KiruyaMomochi/RediveExtract
        file: RediveExtract.zip
    - name: Extract RediveExtract
      run: Expand-Archive ./RediveExtract.zip
    - name: Run
      run: ./RediveExtract/RediveExtract.exe --config ./RediveData/config.json --output RediveData
    - name: Commit Files and Prepare Dispatch
      id: kyaru
      working-directory: "./RediveData"
      run: |
        if ((git status './manifest/masterdata_assetmanifest' -s) -or !(Test-Path db)) {
          echo "::set-output name=database::true"
        }
        if ((git status './manifest/storydata_assetmanifest' -s) -or !(Test-Path storydata)) {
          echo "::set-output name=storydata::true"
        }
        pwsh ../Scripts/Commit-Data.ps1 -Type Manifest
    - name: Dispatch Database Fetch
      if: ${{ steps.kyaru.outputs.database }}
      uses: KiruyaMomochi/workflow-dispatch@v1
      with:
        workflow: "database-fetch.yml"
        token: ${{ secrets.REDIVEDATA_ACCESS_TOKEN }}
    - name: Dispatch Storydata Fetch
      if: ${{ steps.kyaru.outputs.storydata }}
      uses: KiruyaMomochi/workflow-dispatch@v1
      with:
        workflow: "storydata-fetch.yml"
        token: ${{ secrets.REDIVEDATA_ACCESS_TOKEN }}
