name: Fetch Latest Storydata

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  fetch-storydata:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout RediveData
      uses: actions/checkout@v2
      with:
        repository: "KiruyaMomochi/RediveData"
        path: "./RediveData"
        token: ${{ secrets.REDIVEDATA_ACCESS_TOKEN }}
        fetch-depth: 5
    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download RediveExtract
      uses: KiruyaMomochi/download-release@v1
      with:
        repo: KiruyaMomochi/RediveExtract
        file: RediveExtract.zip
    - name: Extract RediveExtract
      run: Expand-Archive ./RediveExtract.zip
    - name: Run Script
      working-directory: "./RediveData"
      run: |
        Import-Module ../scripts/ngdive.psm1
        Get-GitAddLines -Path ./manifest/storydata_assetmanifest -Last 1 |
          ConvertFrom-Manifest |
          Where-Object Path -Like '*storydata_[0-9]*' |
          Save-AssetItem -OutputDirectory . |
          Expand-AssetItem -Program ${{ github.workspace }}/RediveExtract/RediveExtract.exe -OutputDirectory ./storydata
    - name: Commit Files
      working-directory: "./RediveData"
      run: |
        Import-Module ../scripts/ngdive.psm1
        git pull
        Invoke-RediveCommit -Type StoryData
        git push
